"""empty message

Revision ID: 1098f2d566e3
Revises: d9ab9f931e2f
Create Date: 2021-09-15 01:05:44.444961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1098f2d566e3'
down_revision = 'd9ab9f931e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('body_data', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'body_data', 'user', ['user_id'], ['id'])
    op.drop_constraint('user_body_data_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'body_data_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('body_data_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_body_data_id_fkey', 'user', 'body_data', ['body_data_id'], ['id'])
    op.drop_constraint(None, 'body_data', type_='foreignkey')
    op.drop_column('body_data', 'user_id')
    # ### end Alembic commands ###
