"""empty message

Revision ID: a2560e4d4e00
Revises: 1098f2d566e3
Create Date: 2021-09-15 09:05:28.807790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2560e4d4e00'
down_revision = '1098f2d566e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('body_data', 'sm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('body_data', sa.Column('sm', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
