"""empty message

Revision ID: d9ab9f931e2f
Revises: e3561fb016e0
Create Date: 2021-09-15 01:02:03.437500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ab9f931e2f'
down_revision = 'e3561fb016e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('bmi', sa.Integer(), nullable=True),
    sa.Column('sm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('body_data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'body_data', ['body_data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'body_data_id')
    op.drop_table('body_data')
    # ### end Alembic commands ###
